App\Application\Doctrine\Entity\DoctrineSeason:
    type: entity
    table: season

    id:
        id:
            type: string
            generator: { strategy: NONE }
    fields:
        number:
            type: integer
            unique: true
        images:
            type: array
            nullable: true
        year:
            type: string
            length: 255
            nullable: true
        description:
            type: array
            nullable: true
        note:
            type: string
            length: 255
            nullable: true
        seasonShow:
            type: string
            length: 255
            nullable: true
        seen:
            type: boolean
            default: false
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        serie:
            targetEntity: DoctrineSerie
            joinColumn:
                name: serie
                referencedColumnName: id
            nullable: true
    oneToMany:
        episodes:
            targetEntity: DoctrineEpisode
            orphanRemoval: true
            mappedBy: season
            cascade: ["persist"]
            nullable: true
    oneToOne:
        lastEpisodeSeen:
            targetEntity: DoctrineEpisode
            joinColumn:
                name: lastEpisodeSeen
                referencedColumnName: id
            nullable: true