App\Application\Doctrine\Entity\DoctrineUser:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      nullable: true
      length: 100
    password:
      type: string
      length: 255
    roles:
      type: array
      default: 'ROLE_USER'
  oneToMany:
    favorites:
      targetEntity: DoctrineFavorite
      mappedBy: user
      cascade: ["persist"]
